apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nb2RiOjI3MDE3L211Y2hfdG9kb19kYj9hdXRoU291cmNlPWFkbWlu